### ISSUE TITLE
Implement Repository Junction workflow when JATS switch made 

### ISSUE THREAD

**Issue by Melissa37** [elifesciences/JATs-xml#23]

**Comment by gnott** [comment]
Current suggestion,

If we are to not send revisions of articles to Pub Router, then we could attach this to the end of the Pubmed deposit workflow. If a pubmed XML is published that is not a revision and is a VoR, then FTP a full record of the article to Pub Router.
 
This is probably the best set of criteria rather than triggering a delivery immediately after a zip file is uploaded to the bucket.

**Comment by Melissa37** [comment]
This is done, so closing the ticket :-)
